# HTTP
quarkus.http.port=18080

# Datasource (PostgreSQL)
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=vehicle_user
quarkus.datasource.password=vehicle_pass
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/vehicle_db

# Hibernate ORM
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import.sql
quarkus.hibernate-orm.log.sql=true

# gRPC
quarkus.grpc.server.port=9000
quarkus.grpc.server.use-separate-server=true

# Health
quarkus.smallrye-health.root-path=/q/health

# Métricas
quarkus.micrometer.export.prometheus.path=/q/metrics
quarkus.micrometer.binder.jvm=true
quarkus.micrometer.binder.http-server.enabled=true

# OpenAPI / Swagger UI
quarkus.smallrye-openapi.path=/q/openapi
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/q/swagger-ui

# Native image
quarkus.native.container-build=true
