kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: vehicle-reservation-cluster
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 30080
        hostPort: 18080
        protocol: TCP
      - containerPort: 30090
        hostPort: 9000
        protocol: TCP
